import Head from 'next/head'

import { StateContextProvider } from './_app'
import styles from '../styles/Home.module.css'
import { FormSearch } from '../components/FormSearch'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StateContextProvider>
      <main className={styles.main}>
        <FormSearch />
      </main>
      </StateContextProvider>
    </div>
  )
}
